### ISSUE TITLE
popUpTo causes crash after navigating back and trying to navigate again

### ISSUE THREAD

**Issue by ghost** [googlecodelabs/android-navigation#28]
I have navigation graph like this: 
```xml
<navigation xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/main_nav"
    app:startDestination="@id/collectionFragment">
    <fragment
        android:id="@+id/collectionFragment"
        android:name="com.antanassepikas.navbug.CollectionFragment"
        android:label="fragment_collection"
        tools:layout="@layout/fragment_collection" >
        <action
            android:id="@+id/action_collectionFragment_to_viewFragment"
            app:destination="@id/viewFragment" />
    </fragment>
    <fragment
        android:id="@+id/viewFragment"
        android:name="com.antanassepikas.navbug.ViewFragment"
        android:label="fragment_view"
        tools:layout="@layout/fragment_view" >
        <action
            android:id="@+id/action_viewFragment_to_editFragment"
            app:destination="@id/editFragment" />
    </fragment>
    <fragment
        android:id="@+id/editFragment"
        android:name="com.antanassepikas.navbug.EditFragment"
        android:label="fragment_edit"
        tools:layout="@layout/fragment_edit" >
        <action
            android:id="@+id/action_editFragment_to_viewFragment"
            app:destination="@id/viewFragment"
            app:popUpTo="@+id/viewFragment"
            app:popUpToInclusive="true" />
    </fragment>
</navigation>
```

Note that the last action has 

```
app:popUpTo="@+id/viewFragment"
app:popUpToInclusive="true" 
```

When navigated back from the last action this should open fragment previous to viewFragment instead of whatever the actual backstack is - And it does just that.

However event though @+id/collectionFragment after "Back Button" is opened and visible, further navigation actions cause crash. 
```
java.lang.IllegalArgumentException: navigation destination com.antanassepikas.navbug:id/action_collectionFragment_to_viewFragment is unknown to this NavController 
at androidx.navigation.NavController.navigate(NavController.java:669) 
at androidx.navigation.NavController.navigate(NavController.java:628) 
at androidx.navigation.NavController.navigate(NavController.java:616) 
at com.antanassepikas.navbug.CollectionFragment$onCreateView$$inlined$apply$lambda$1.onClick(CollectionFragment.kt:17) at android.view.View.performClick(View.java:6891) 
at android.widget.TextView.performClick(TextView.java:12651)
at android.view.View$PerformClick.run(View.java:26083) 
at android.os.Handler.handleCallback(Handler.java:789) 
at android.os.Handler.dispatchMessage(Handler.java:98) 
at android.os.Looper.loop(Looper.java:164) at android.app.ActivityThread.main(ActivityThread.java:6938) 
at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
```

I think this has to do something with destination not being changed correctly, because when printing out what destinations change during this action cycle cycle this is what I see:

```
0 -  com.antanassepikas.navbug:id/collectionFragment // when collection fragment is opened by default
1 -  com.antanassepikas.navbug:id/viewFragment // when navigating from collection to item
2 -  com.antanassepikas.navbug:id/editFragment // when navigating from item view to item edit
3 -  com.antanassepikas.navbug:id/viewFragment // when navigating from item edit to item view
4 -  com.antanassepikas.navbug:id/collectionFragment // this destinations happens automatically
5 -  com.antanassepikas.navbug:id/viewFragment // this destinations happens automatically
```
At this point viewFragment is open and when "Back Button" is clicked collectionFragment is opened which is what is to be expected, but now when trying to opening another item a crash happens.

I created sample project where this is reproducible https://github.com/sepikas/navigation-bug

**Comment by ghost** [comment]
I just realised that this is not where this bug should be reported.
